[2024-09-19T00:46:40.862+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T00:46:41.012+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-19T00:46:40.253456+00:00 [queued]>
[2024-09-19T00:46:41.035+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-19T00:46:40.253456+00:00 [queued]>
[2024-09-19T00:46:41.036+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-19T00:46:41.067+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_data_ingestion> on 2024-09-19 00:46:40.253456+00:00
[2024-09-19T00:46:41.086+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_ingestion', 'manual__2024-09-19T00:46:40.253456+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmpny1qz68h']
[2024-09-19T00:46:41.094+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask run_data_ingestion
[2024-09-19T00:46:41.098+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=273) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-19T00:46:41.099+0000] {standard_task_runner.py:72} INFO - Started process 274 to run task
[2024-09-19T00:46:41.175+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_ingestion manual__2024-09-19T00:46:40.253456+00:00 [running]> on host 60f4d263d5b1
[2024-09-19T00:46:41.321+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T00:46:40.253456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T00:46:40.253456+00:00'
[2024-09-19T00:46:41.323+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T00:46:41.358+0000] {docker.py:367} INFO - Starting docker container from image us-west1-docker.pkg.dev/nba-fantasy-ml/nba-data-pipeline-repo/data-ingestion:latest
[2024-09-19T00:46:41.370+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-19T00:47:14.483+0000] {docker.py:438} INFO - Processing batch 1/1
[2024-09-19T00:47:14.484+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406060BOS.html for game date 2024-06-06
[2024-09-19T00:47:14.485+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406090BOS.html for game date 2024-06-09
[2024-09-19T00:47:14.485+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406120DAL.html for game date 2024-06-12
[2024-09-19T00:47:14.486+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406140DAL.html for game date 2024-06-14
[2024-09-19T00:47:14.486+0000] {docker.py:438} INFO - Scraping box score: https://www.basketball-reference.com/boxscores/202406170BOS.html for game date 2024-06-17
[2024-09-19T00:47:14.487+0000] {docker.py:438} INFO - 2024-09-19 00:47:14,481 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd08909d1b0>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:47:14.887+0000] {docker.py:438} INFO - 2024-09-19 00:47:14,886 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd087f87970>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:47:15.694+0000] {docker.py:438} INFO - 2024-09-19 00:47:15,692 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd089915270>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:47:17.301+0000] {docker.py:438} INFO - 2024-09-19 00:47:17,298 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd087fb0190>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:47:20.510+0000] {docker.py:438} INFO - 2024-09-19 00:47:20,508 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd087fb03a0>: Failed to resolve 'minio' ([Errno -2] Name or service not known)")': /nba-raw-data?location=
[2024-09-19T00:47:20.515+0000] {docker.py:438} INFO - Failed to upload player_box_scores/2023-24/nba_player_stats_2023-24_2024-06-01_to_2024-06-30_2024-09-19_00-47-14.csv: HTTPConnectionPool(host='minio', port=9000): Max retries exceeded with url: /nba-raw-data?location= (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fd087fb0550>: Failed to resolve 'minio' ([Errno -2] Name or service not known)"))
[2024-09-19T00:47:20.515+0000] {docker.py:438} INFO - 2024-09-19 00:47:20,513 - INFO - Data successfully uploaded to MinIO bucket 'nba-raw-data' as 'player_box_scores/2023-24/nba_player_stats_2023-24_2024-06-01_to_2024-06-30_2024-09-19_00-47-14.csv'
[2024-09-19T00:47:20.516+0000] {docker.py:438} INFO - 2024-09-19 00:47:20,513 - INFO - Data ingestion completed successfully
[2024-09-19T00:47:20.813+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T00:47:20.813+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_ingestion, run_id=manual__2024-09-19T00:46:40.253456+00:00, execution_date=20240919T004640, start_date=20240919T004641, end_date=20240919T004720
[2024-09-19T00:47:20.851+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T00:47:20.876+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-19T00:47:20.877+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
