[2024-09-19T09:17:22.265+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T09:17:22.286+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T09:13:25.420482+00:00 [queued]>
[2024-09-19T09:17:22.300+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T09:13:25.420482+00:00 [queued]>
[2024-09-19T09:17:22.300+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 5
[2024-09-19T09:17:22.317+0000] {taskinstance.py:2888} INFO - Executing <Task(DockerOperator): run_data_processing> on 2024-09-19 09:13:25.420482+00:00
[2024-09-19T09:17:22.326+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'nba_data_pipeline', 'run_data_processing', 'manual__2024-09-19T09:13:25.420482+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmpq69o7_9a']
[2024-09-19T09:17:22.329+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask run_data_processing
[2024-09-19T09:17:22.331+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-19T09:17:22.333+0000] {standard_task_runner.py:72} INFO - Started process 256 to run task
[2024-09-19T09:17:22.388+0000] {task_command.py:467} INFO - Running <TaskInstance: nba_data_pipeline.run_data_processing manual__2024-09-19T09:13:25.420482+00:00 [running]> on host 76dded199c5f
[2024-09-19T09:17:22.507+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_processing' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T09:13:25.420482+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-19T09:13:25.420482+00:00'
[2024-09-19T09:17:22.508+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T09:17:22.544+0000] {docker.py:367} INFO - Starting docker container from image us-west1-docker.pkg.dev/nba-fantasy-ml/nba-data-pipeline-repo/data-processing:latest
[2024-09-19T09:17:22.558+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-09-19T09:17:23.442+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,441 - INFO - Starting data processing...
[2024-09-19T09:17:23.446+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,445 - INFO - Database connected.
[2024-09-19T09:17:23.447+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,445 - INFO - Cleaning and preprocessing data...
[2024-09-19T09:17:23.485+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,483 - INFO - Validation passed.
[2024-09-19T09:17:23.486+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,483 - INFO - Assigning unique IDs for players and games...
[2024-09-19T09:17:23.624+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,623 - INFO - Inserting player stats into database...
[2024-09-19T09:17:23.633+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,631 - ERROR - Error processing raw data: duplicate key value violates unique constraint "playerstats_pkey"
[2024-09-19T09:17:23.634+0000] {docker.py:438} INFO - DETAIL:  Key (game_id, player_id)=(ffdecbe4171e4829937e63a32f0d0dad, 1) already exists.
[2024-09-19T09:17:23.634+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,632 - INFO - Database connection closed.
[2024-09-19T09:17:23.635+0000] {docker.py:438} INFO - 2024-09-19 09:17:23,632 - ERROR - Data processing failed.
[2024-09-19T09:17:23.939+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T09:17:23.939+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nba_data_pipeline, task_id=run_data_processing, run_id=manual__2024-09-19T09:13:25.420482+00:00, execution_date=20240919T091325, start_date=20240919T091722, end_date=20240919T091723
[2024-09-19T09:17:23.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T09:17:23.993+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-19T09:17:23.995+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
